[package]
name = "arx-core"
version = "0.1.4"
edition = "2024"
description = "The Core of Packet Manager ARX"

repository = "https://github.com/DanielHunter3/arx-core"
readme = "README.md"
license = "AGPL-3.0"

[dependencies]

# Асинхронность и сети
tokio = { version = "1.35", features = ["full"] }     # асинхронность
reqwest = { version = "0.11", features = ["stream"] } # для загрузки

# Работа с .tar.zst
tar = "0.4"
zstd = "0.13"

# Конфигурация
semver = { version = "1.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }

# Зависимости
pubgrub = "0.3"    # алгоритм разрешения зависимостей

# Сигнатуры и безопасность
ring = "0.17"           # криптография
async-signature = "0.3" # подписи

# Обработка ошибок
thiserror = "2.0.17"

[features]
default = ["user"]  # По умолчанию пользовательский режим
user = []           # Для разработки
system = []         # Для продакшена
